type prefer.prm          > suppose.prm
type ppif.prm           >> suppose.prm
type commands.prm       >> suppose.prm
type program.prm        >> suppose.prm
type variants.prm       >> suppose.prm
type mdoutputs.prm      >> suppose.prm
type basekeys.kwd       >> suppose.prm
type voleqnum.kwd       >> suppose.prm
type ardwrd3.kwd        >> suppose.prm
type armwrd3.kwd        >> suppose.prm
type phewrd3.kwd        >> suppose.prm
type wrd3.prm           >> suppose.prm
type wsbwd.kwd          >> suppose.prm
type dbs.kwd            >> suppose.prm
type dfb.kwd            >> suppose.prm
type climate.kwd        >> suppose.prm
type fire.kwd           >> suppose.prm
type lpmpb.kwd          >> suppose.prm
type brust.kwd          >> suppose.prm
type cond.rul           >> suppose.prm
type cover.kwd          >> suppose.prm
type estab.kwd          >> suppose.prm
type bgc.kwd            >> suppose.prm
type org.kwd            >> suppose.prm
type exten.prm          >> suppose.prm
type forest.prm         >> suppose.prm
type function.evm       >> suppose.prm
type keycats.prm        >> suppose.prm
type keylist.prm        >> suppose.prm
type manage.prm         >> suppose.prm
type mgmtcats.prm       >> suppose.prm
type modifiers.prm      >> suppose.prm
type modelmodf.prm      >> suppose.prm
type unevage.prm        >> suppose.prm
type inttrtmt.prm       >> suppose.prm
type fueltrt.prm        >> suppose.prm
type mist.kwd           >> suppose.prm
type runwiz.prm         >> suppose.prm
type species.prm        >> suppose.prm
type tutorial.prm       >> suppose.prm
type variable.evm       >> suppose.prm
type HabPa_bm.prm       >> suppose.prm
type HabPa_ca.prm       >> suppose.prm
type HabPa_oc.prm       >> suppose.prm
type HabPa_ci.prm       >> suppose.prm
type HabPa_ec.prm       >> suppose.prm
type HabPa_em.prm       >> suppose.prm
type HabPa_ie.prm       >> suppose.prm
type HabPa_kt.prm       >> suppose.prm
type HabPa_ls.prm       >> suppose.prm
type HabPa_ni.prm       >> suppose.prm
type HabPa_pn.prm       >> suppose.prm
type HabPa_op.prm       >> suppose.prm
type HabPa_sn.prm       >> suppose.prm
type HabPa_so.prm       >> suppose.prm
type HabPa_ut.prm       >> suppose.prm
type HabPa_wc.prm       >> suppose.prm
type econ.kwd           >> suppose.prm

rem copy suppose.prm c:\fvsbin\suppose.prm
rem move ..\suppose.prm c:\N\fvsbin\suppose.prm




