/********************************************************************
 *
   File Name:   appdef.hpp
   Author:      This file was generated by Layout 1.0
   Date:        Tue Aug 23 13:31:15 1994  (This marks the beginning
                time and date for coding of Suppose).
                                                                    *
 ********************************************************************/

#ifndef AppDef_H
#define AppDef_H

#include <limits.h>
#include "PwrDef.h"

#define CsupposeAppID   PWRClassIDBase + 501
#define CsupposeDocID   PWRClassIDBase + 502
#define CsupposeWinID   PWRClassIDBase + 503
#define CWwindowWinID   PWRClassIDBase + 504


#define SPLEFT  0
#define SPRIGHT 1

#endif // AppDef_H
